export const FETCH_REPORT = 'FETCH_REPORT'
export const FETCH_REPORT_LOADING = 'FETCH_REPORT_LOADING'
export const FETCH_REPORT_ERROR = 'FETCH_REPORT_ERROR'

export const FETCH_WAZE_ALERT = 'FETCH_WAZE_ALERT'
export const FETCH_WAZE_ALERT_LOADING = 'FETCH_WAZE_ALERT_LOADING'
export const FETCH_WAZE_ALERT_ERROR = 'FETCH_WAZE_ALERT_ERROR'